[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://question-form-rcqc.onrender.com"
    Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"